### ISSUE TITLE
Need explanation of settings

### ISSUE THREAD

**Issue by Envergure** [martin2250/GrblHeightProbe2#8]
I am fairly new to CNC and I'm not sure what the ProbeRetraction and ProbePlunge settings mean.  I I'm afraid to change them to find out.  Could someone explain them to me?

**Comment by martin2250** [comment]
Hi, welcome to the world of CNC :)

Probe Retraction is the distance in mm that the bit will pull back (up) after it has touched the surface of the material. So if your bit touches the surface at Z1.4 and Probe Retraction is set to 0.5mm, the bit will travel to Z1.9 before moving on to the next point.  
For flat material (most PCBs and metal plates) you can set it very low (0.2mm) .This also depends on the machine itself. For more uneven surfaces (eg. probing a coin to get an accurate 3D-model you should set this to at least the maximum dZ you expect between two adjacent points plus some room for error.  

Probe plunge is the speed at which the probe travels downward. Remember that your machine has momentum so it won't stop immediately. 25mm/min is a good starting point, lower speeds result in more accuracy and less pressure on the bit. Faster speeds are less accurate and may damage your bits (25mm/min is still far from damaging even very fine bits).
Also depends on the acceleration profile of the Z-axis.  
If you feel like experimenting, take a pice of copper wire, sharpen it to a very fine point and use it as a probe tip. Since copper is very soft you can push the plunge rate pretty high without risking a bit or your machine. You'll also see any damage to the tip much earlier than on a hss or carbide tip, so if the copper is fine, your bits will be too.

I really should start working on the wiki.
